### ISSUE TITLE
Don't reset the developer tool views when switching between them

### ISSUE THREAD

**Issue by kellerza** [home-assistant/home-assistant-polymer#124]
Since the web optimization, if you switch developer tab tools, the complete view gets re-built.

It would be nice if data entered in these views are not lost when switching between them.

During testing there is a lot of switching between "Templates", "Entities", "Services", "Events" and copying data between them. If they reset it slows down this process significantly

**Comment by balloob** [comment]
The problem is [here](https://github.com/home-assistant/home-assistant-polymer/blob/master/src/layouts/home-assistant-main.html#L28-L49). Right now all non-states panels will be resolved in the `partial-panel-resolver`, which will remove panels that are no longer used from the DOM.

It would be better if it would hide the old element and render the new one. Only downside there is that the hidden elements would still be subscribed to the data and thus each update will cause a lot of updates. This means that each panel will have to be aware if it is visible or not and unsubscribe if that is the case.

Extra bonus: the related Pivotal story: https://www.pivotaltracker.com/story/show/127563225

**Comment by justweb1** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/master/src/layouts/partial-panel-resolver.html#L88-L94

I think this is the code that would need to be updated.

**Comment by justweb1** [comment]
I think this one is a little beyond my understanding at this point. I'll watch it to learn though.

**Comment by justweb1** [comment]
@balloob Could we save the state with local storage?

**Comment by justweb1** [comment]
@kellerza @balloob `<app-localstorage-document>` works to fix this issue. See #130

**Comment by kellerza** [comment]
Works very well for services, thanks @justweb1! 

It would be a nice to have for events and states, but services really are the most used.
