### ISSUE TITLE
Remove the label "attribution" from cards

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/home-assistant-polymer#141]
After the PR [#3719 ](https://github.com/home-assistant/home-assistant/pull/3719), the sensor cards have a redundant label "attribution", which does not look pretty (see cards below). 

![image](https://cloud.githubusercontent.com/assets/18319734/19659482/1c15fa16-99fa-11e6-990f-817c0580982c.png)

We can leave the attribution, but remove the label "attribution" from the cards.

**Comment by justweb1** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/master/src/more-infos/more-info-default.html#L17-L18

It looks like that is provided by the background as a heading. Since this is the default layout, the only thing I can potentially do is hide that field if it is equal to Attribution. Making this change may have adverse affects on styling and other elements. Maybe that heading can be changed on the background to something more appropriate as an alternate fix. 

@balloob What is your opinion on this?

**Comment by balloob** [comment]
I like the idea to hide the attribution from the default attribute renderer as long as we make sure that it is shown below the other attributes (but without the attribution caption).

**Comment by andela-oesho** [comment]
@justweb1 I would be claiming this issue

**Comment by justweb1** [comment]
@andela-oesho Have at it. Happy to have another front-end dev.

**Comment by justweb1** [comment]
@andela-oesho We also have a dev chat if you need any assistance.
https://gitter.im/home-assistant/home-assistant/devs

**Comment by andela-oesho** [comment]
alright thanks a bunch @justweb1  will get started
