### ISSUE TITLE
Like entities in groups that use to be able to be set as one are no longer

### ISSUE THREAD

**Issue by mealan** [home-assistant/home-assistant-polymer#1589]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
71.0

**Browser and Operating System:**
 All, multiple 
For windows, Chrome, firefox, internet explorer, edge
for mac, chrome, safari
for ios, chrome, safari

HA Host os is multiple, hass.io on ubuntu x64, Debian Squeeze, virtualenv, installed with pip, 

**Description of problem:**
In previous versions of Home Assistant you could click on the header of a group only consisting of lights and then dim or change the color of all the lights in the group. This is no longer possible and throws an error. (use to throw an error before .76.0)(The color wheel and brightness slider don't appear anymore.)

*appears not working in lovelace either*

**Javascript errors shown in the web inspector (if applicable):**
```
appears to be no errors.
```

**Additional information:**
Lifx groups here
https://github.com/home-assistant/home-assistant/issues/15533

and more information from here.
https://github.com/home-assistant/home-assistant-polymer/issues/1466

**Comment by awarecan** [comment]
> This is no longer possible and throws an error.

> appears to be no errors.

Do you have error or not?

**Comment by mealan** [comment]
before 76 it does, now it does not, I believe you are aware of that.

**Comment by mealan** [comment]
@balloob or anyone else, is this expected behavior going forward?

**Comment by mealan** [comment]
@awarecan

**Comment by smuggyuk** [comment]
The details are all in 1466, which was closed because the "fix" was to stop the error appearing in the JS log, rather than actually addressing the underlying issue which is that the colour wheel and brightness sliders no longer appear in a group that contains lights.  Hence, this issue has been created to address the "original" issue, that still isn't resolved.  There aren't many details here because frankly, they're all on https://github.com/home-assistant/home-assistant-polymer/issues/1466

There isn't a log or error to include here because the fix applied in 1466 removed the error that was appearing, without putting the colour wheel and brightness slider back.

We're tagging people because there appears to be no response or appetite to resolve this, even though it affects Lovelace, and some acknowledgement that there is an issue here would be appreciated.

light.group isn't a suitable workaround as that removes the ability to turn on/turn off the individual lights within the group, so still means you have to include the individual light entities somewhere in your UI to control them individually - using standard groups got around this limitation quite nicely, until it stopped working.

I appreciate in the grand scheme of life it isn't that important, but acknowledgement of the issue and that it will/won't be fixed is all we're really asking for here at this stage.

**Comment by schumpeter2** [comment]
I'm also experiencing this issue and would like to see the dimming & color wheel controls restored to group headers. There is not an equivalent UI mechanism that allows both simultaneous and individual control of groups of lights in a way that is intuitive (clicking on the header to control all lights within the group).

**Comment by mealan** [comment]
so yeah, any comments now orrrrrrrrrrr just like switch to smart things or what? I don't want to, but if this is what happens when there's an actual problem it kinda seems like we have no choice.

**Comment by sgripsga** [comment]
Seems like there won’t be any acknowledgement of the issue. So I guess it will not be fixed....?

**Comment by schumpeter2** [comment]
It looks like the issue is related to this portion of more-info-group.js:
https://github.com/home-assistant/home-assistant-polymer/blob/433b1e297946ef80c278d3267edc46f33b1ced76/src/dialogs/more-info/controls/more-info-group.js#L101-L105
In the case of a group containing only lights, `stateMoreInfoType(groupDomainStateObj).toUpperCase()` should return 'LIGHT' so that the more-info-light dialog is called. If I manually edit this line to specify 'MORE-INFO-LIGHT', I get the expected behavior for a group of lights in version 0.77.3:

![screenshot_20180915_112823](https://user-images.githubusercontent.com/26562279/45589470-d7efd300-b8da-11e8-88a5-7acd989b5a65.png)

**Comment by mealan** [comment]
Super awesome find, now if they actually do anything with it would be the bigger question. Since it's impossible task to even get someone to state if this is the new desired behavior or not.

**Comment by cgarwood** [comment]
@schumpeter2 is correct. the stateMoreInfoType function is returning `GROUP` for all groups, modifying it to return `LIGHT` fixes groups of lights, but of course breaks it for non-light groups.

I looked back at the file history and don't see any changes that should have changed the behavior.

I don't have a lot of knowledge of the inner workings of the more-info-group code and likely won't have time to dig in anytime soon, but anyone else is welcome to submit a PR with a fix.
