### ISSUE TITLE
Dialogs appear and then move up ~10 pixels

### ISSUE THREAD

**Issue by jbcodemonkey** [home-assistant/home-assistant-polymer#184]
Windows 10, Chrome and Edge.
HA 0.36.1 back to 0.34.0 (maybe earlier).

Position when first opening a Dialog:
![image](https://cloud.githubusercontent.com/assets/4581542/22309472/659627ac-e319-11e6-9938-46ee78f4ba1c.png)

Position a second after a Dialog opens (it moves up):
![image](https://cloud.githubusercontent.com/assets/4581542/22309483/707efca2-e319-11e6-850c-a80f213ea6b6.png)

It appears and then moves up several pixels.
Reloading the same dialog opens it to the higher position, no movement.

**Comment by balloob** [comment]
It's because the history still has to load the first time. We don't know how much space it is going to take (depends on the entity and if data is stored etc). So after the history is loaded we make sure the dialog gets centered again.

There is nothing we can do about this. Marking this a wontfix.

**Comment by balloob** [comment]
Actually, realized it is not because of the history but because of how the light more info dialog works. Since changing a state object can cause the height to change. Made it now that it will only reposition the dialog when the dialog gets rerendered, no longer on first render.

5792c7710010c165d6ff8b69f3176577387420cb
