### ISSUE TITLE
Time formatting not following browser locale settings in state history chart timeline

### ISSUE THREAD

**Issue by sillevl** [home-assistant/home-assistant-polymer#196]
As stated in https://github.com/home-assistant/home-assistant/issues/184#issue-89103971, the formatting of time is inconsistent in the state history chart timeline. With browser settings set to 'nl', the time is still formated in am/pm format, not in 24h format. 

This problem existed also in the logbook (https://github.com/home-assistant/home-assistant/issues/184#issue-89103971) and was fixed in #170. I believe a similar solution could be build for this issue. 

The `window.hassUtil.formatTime` function could be used that was changed in #170 as it takes the locale setting into account when formatting dates and times. (see https://github.com/michaelarnauts/home-assistant-polymer/blob/842c5d5e89960e1bf432b210c84af69ecb424d58/src/util/hass-util.html#L132)

**Comment by michaelarnauts** [comment]
Can you attach a screenshot of the location where the time is still displayed incorrectly?

**Comment by sillevl** [comment]
![schermopname 47](https://cloud.githubusercontent.com/assets/979071/22664180/c96cd97a-ecaf-11e6-9190-a3dd0db984c3.png)

Next to 'Keuken' it says '7:45 a.m. - 5:21 p.m.' This should be '7:45 - 17:21'

**Comment by michaelarnauts** [comment]
Alright, I see it also now, I didn't hover over the timeline... I'll take a look at it :)

**Comment by armills** [comment]
The other portion is the actual timeline labels. They are currently hard-coded to 24 hours, no matter the locale. This is true anywhere we use google charts.

**Comment by michaelarnauts** [comment]
It seems you need to initialise the google charts with a language. By default this is `en`. (from: https://developers.google.com/chart/interactive/docs/basic_load_libs#loadwithlocale)

This should do the trick, but I'm unable to test since I'm having issues downloading python dependencies...

```patch
diff --git a/src/components/state-history-charts.html b/src/components/state-history-charts.html
index 3755040..d64e57c 100644
--- a/src/components/state-history-charts.html
+++ b/src/components/state-history-charts.html
@@ -85,6 +85,7 @@ Polymer({
   _googleApiLoaded: function () {
     window.google.load('visualization', '1', {
       packages: ['timeline', 'corechart'],
+      language: window.hassUtil.LANGUAGE,
       callback: function () {
         this._apiLoaded = true;
       }.bind(this),
```

**Comment by armills** [comment]
The problem is here: https://github.com/home-assistant/home-assistant-polymer/blob/master/src/components/state-history-chart-line.html#L94 (and equivalent for timeline) where the format is hard-coded.

As I understand, the reason it's hard-coded is that google charts doesn't have an easy way to display a short time string in the locale preferred way.

**Comment by michaelarnauts** [comment]
@armills indeed, that's the second issue where the times on the h-axis are forced to 24h.

**Comment by armills** [comment]
Ah you're right. For some reason I was thinking of the other problem. Adding the language will be good. 👍

**Comment by tobsch** [comment]
+1

**Comment by fantaaaaaa** [comment]
is this still on the map? quite confusing for 24h-formatted users as me in europe :)

**Comment by kaiomatico** [comment]
Can anyone please test the solution from @michaelarnauts ? I live in Germany and would like to have the logbook in 24h format, just like the rest of the ui properly does change to 24h when setting the correct language.

**Comment by andrey-git** [comment]
In #847 I'm passing `navigator.language`

**Comment by kaiomatico** [comment]
That's probably also a good alternative to language: window.hassUtil.LANGUAGE, , but does #847 also fix the logbook/history? Sorry if this is a dumb question

**Comment by andrey-git** [comment]
window.hassUtil.LANGUAGE is not defined.
#847 will fix history.

Logbook is already using navigator.language

**Comment by michaelarnauts** [comment]
There was a hassUtil.LANGUAGE, that took care of some browser differences since navigator.language didn't work the same on all browsers.

**Comment by mcspr** [comment]
Upgrading to 0.64, new Chart.js timeline no longer using 24 hour style as google charts did:
(Using ru-RU locale in the screenshot)
![default](https://user-images.githubusercontent.com/132763/36707245-805689bc-1b7e-11e8-9699-c840a8d4f014.png)

At least for tooltip, I noticed that it is using `moment.format` with locale based output. But there are no locales! Maybe this has something to do with packaging? (include `moment-with-locales.js` instead of `moment.js`)
https://github.com/home-assistant/home-assistant-polymer/blob/0ab240c678260e5ec9924407440415e3679f282f/src/components/entity/ha-chart-base.html#L202-L208
![default](https://user-images.githubusercontent.com/132763/36707532-bde33d2e-1b7f-11e8-8165-9cbb74735e6e.png)

**Comment by c727** [comment]
@mcspr please create a new issue for this a we replaced the chart component
