### ISSUE TITLE
Lovelace: sensor card: incorrect sampling

### ISSUE THREAD

**Issue by bmesuere** [home-assistant/home-assistant-polymer#2010]
The sensor card by design samples only a few values from the history to create its graph. These samples are uniformly selected from the total set of measured values. Because home assistant only stores/returns changes in values, the resulting samples are not equidistant in time, but they are plotted that way. This means that for a temperature sensor that hardly changes during the night, but has an updated values every minute or so when the heating turns on, the resulting graph on the sensor card incorrectly stretches out the period with a lot of updates.

Example:
![image](https://user-images.githubusercontent.com/481872/48131075-15476000-e28f-11e8-8bce-ecbcb1008097.png)
![image](https://user-images.githubusercontent.com/481872/48131096-2c864d80-e28f-11e8-9690-4d2ef87bdb97.png)

There are 2 possible solutions: 
- take into account the time when sampling the data from history and sample at equidistant times
- take into account the timestamp of the sampled values when drawing the graph

I have a preference for the second solution because this would result in a higher resolution when the sensor value changes a lot.

**Comment by balloob** [comment]
Aah, good old interpolation. Never ending fun there! 🙈 

> Because home assistant only stores/returns changes in values

This is not 100% correct. The default behavior is to do this but the property `force_update` can be overriden on entities (in the code) to return `True` if you know that the current value is actually a new measurement and not a cached old measurement.

However, none of our graphs take this into consideration because we have no way currently to store that each change is a new measurement. So to avoid confusion, we disable interpolation for the graphs shown in the history panel and more info dialog.

**Comment by bmesuere** [comment]
I can confirm this was fixed by #2069. Thanks!
