### ISSUE TITLE
Light element doesn't scale down in a horizontal group

### ISSUE THREAD

**Issue by mlevit** [home-assistant/home-assistant-polymer#2334]
**Home Assistant release with the issue:** 0.83.*

**Last working Home Assistant release (if known):** N/A

**Browser and Operating System:** Google Chrome 70.0.3538.110 / macOS 10.14.2

**Description of problem:** The Light element doesn't scale properly when in a horizontal group

![image](https://user-images.githubusercontent.com/233717/50047621-1e88df80-010d-11e9-8c5f-f31d59c5c55c.png)

**Javascript errors shown in the web inspector (if applicable):**
```
N/A
```

**Additional information:**

**Comment by kmlucy** [comment]
Has there any progress with this? I'd love to switch my entity buttons for light cards, but all my lights are in horizontal stacks.

**Comment by TheLastProject** [comment]
I've been looking into it because I have the same issue and the issue happens if the width of the `<ha-card>` for the light card is less than 160px.

In my case, it would be 147px.

If I then change:
`<div id="light" class="rs-firefox rs-control" style="height: 160px; width: 160px;"><div class="rs-container full pie" style="height: 160px; width: 160px;">...`
to
`<div id="light" class="rs-firefox rs-control" style="height: 160px; width: 147px;"><div class="rs-container full pie" style="height: 147px; width: 147px;">...`
it fixes the display issue:
![image](https://user-images.githubusercontent.com/1885159/57971154-80829500-798a-11e9-9e94-034e8850723d.png)
(left: fix applied, right: old code)

This should probably be a relatively simple thing to fix for anyone who understands how this HTML gets generated, but I sadly can't find where in the code it decides to set the height and width values.

Hopefully someone who does understand Polymer sees this though and applies the fix.

**Comment by klejejs** [comment]
Looks like this has been solved. Can it be closed?
