### ISSUE TITLE
Climate More-info does not allow dual temp target setting

### ISSUE THREAD

**Issue by lekobob** [home-assistant/home-assistant-polymer#236]
When the more-info-climate panel was updated with arrow buttons in place of the slide, there is no way to set a hi and low target.  See demo climate component.

**Comment by balloob** [comment]
Oh, this is a use case that we forgot to handle

CC @sdague

**Comment by balloob** [comment]
I wonder what a solution would be to fix this without having to revert the change. Maybe have two temp selectors below one another?

**Comment by BioSehnsucht** [comment]
I've noticed this is an issue with my EcoBee as well. I can change temp just fine in heat or cool mode, but in auto I can't set anything.

I'm surprised more people haven't noticed / complained, but perhaps most just simply change their thermostat mode twice a year and don't use an auto setting ...

**Comment by jawilson** [comment]
I have my thermostat almost exclusively in heat-cool so it's obnoxious that it's completely unusable via the HASS UI (though my automations usually take care of any adjustments I'd want to make).

I'm looking into this, I think two selectors side-by-side would be nice, otherwise one below each other.

**Comment by ciotlosm** [comment]
This could get fixed by #765 after review is complete. Unsure if the current state of the PR is acceptable considering you get back some control.

**Comment by MartinHjelmare** [comment]
This can be closed.
