### ISSUE TITLE
Logbook: When using an entity filter and refreshing, unrelated entries are shown

### ISSUE THREAD

**Issue by casperklein** [home-assistant/home-assistant-polymer#2384]
**Home Assistant release with the issue:**
 0.84.6 

**Browser and Operating System:**
Windows 10: Firefox 64 & Edge

**Description of problem:**
Logbook: Displaying entries for an entity works as expected:

![pir-1](https://user-images.githubusercontent.com/590174/50423561-720ad400-0857-11e9-9ab3-175f51d3a359.PNG)

But when refreshing using the icon in the upper right corner, unreleated entries are shown:

![pir-2](https://user-images.githubusercontent.com/590174/50423576-96ff4700-0857-11e9-9e33-47da4857557a.PNG)

**Comment by donkristo** [comment]
The same happens when I change the time filter while having an entity filter set. Probably related.

1. Open logbook, by default it is filtered for "1 day"
2. Set an entity filter
3. Set a time filter
4. All entities are shown again although the entity filter is still set

![image](https://user-images.githubusercontent.com/10496260/55854545-4d680d00-5b65-11e9-8cf8-0f1379ff0dd7.png)

**Comment by iantrich** [comment]
should be fixed now
