### ISSUE TITLE
New language request - Icelandic

### ISSUE THREAD

**Issue by samueljon** [home-assistant/home-assistant-polymer#2654]
I would like to translate home-assistant to Icelandic. I have been translating open source software on-and-off for many years for projects such as wordpress, drupal, Gnome Desktop and others. I familiar with the role of being translation coordinator since I served that role for the Gnome Desktop project for several years. 

English Name: Icelandic
Native Name: Íslenska

Language definition as per IANA: 
Type: language
Subtag: is
Description: Icelandic
Added: 2005-10-16
Suppress-Script: Latn

**Comment by samueljon** [comment]
@cgarwood is it possible that both issues where closed without any action ?

**Comment by iantrich** [comment]
@awarecan you want to add this one as well? I'd be willing to learn how to add them as well.

**Comment by awarecan** [comment]
Sure, I can take care it.

**Comment by awarecan** [comment]
@samueljon Icelandic has been added into both front end and back end localization project in https://lokalise.co

Please follow the "joint the team" link in https://developers.home-assistant.io/docs/en/internationalization_translation.html start your translation.

I translated few words in helps from Google/Microsoft in order to make the new language be included in, feel free to change them.

**Comment by samueljon** [comment]
Thanks for the update @awarecan 👍

**Comment by samueljon** [comment]
@awarecan I cannot find Icelandic language in the "Projects – Home Assistant - Backend" is it possible that the support is missing in the backend project ?
