### ISSUE TITLE
0.90.0b4 - No UI refresh with logged in user not in admin group

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#2954]
**Home Assistant release with the issue:**
0.90.0b4

**Last working Home Assistant release (if known):**
Not sure, assuming 0.89.x

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Latest chrome on Ubuntu 18.04

**Description of problem:**
Ui on my tablet doesn't refresh the states of sensor's, switches, ...
Just like a screenshot, nothing changes.
After digging a while, i found out that this happens if the logged in user is in the 'user' group.
Changing the user to 'administrator' group and restarting the browser, all state changes refresh as it should be.

**Comment by SeanPM5** [comment]
Confirmed here as well and I'm on an earlier 0.90b3, so it probably affects all of the 0.90x betas so far. And I reproduced this in the iOS app and desktop browser so I don't think it's tablet or browser-specific either.

It appears that in most (but not all) cases it _does_ actually perform the action, it just doesn't update the UI whatsoever. So if you had an entity-button that toggled a switch, it'd turn on your device but the button wouldn't get updated to the "active" state with yellow icon color etc until the user manually refreshes their browser.

Noticed this while attempting to dismiss a persistent notifications as User account as well, they appear to be "stuck" and never go away, though if you refresh the browser they are gone.

So the problem seems to be that it's not live updating when logged in as User.

A good way to test and reproduce this issue is to be logged in as a user account in one browser (or incognito), and logged in as admin account in another window, then start performing actions on the user account. It will never refresh the UI on the user account, but it will for the admin account.
