### ISSUE TITLE
Person Editor: Allow set person picture (add image entity option to cards with icons)

### ISSUE THREAD

**Issue by ofekashery** [home-assistant/home-assistant-polymer#3021]

**Comment by cwhits** [comment]
I'd also like it if there was an option to set the picture based on a specific device. I use the google device tracker and it automatically pulls my profile picture from google. If I update my google profile picture, it updates that icon as well. It'd be nice if I could pick my `device_tracker.superlonggoogleid` as my default picture instead of having to find and update the URL.

**Comment by bairdj** [comment]
You can set the picture for a person by adding the `entity_picture` attribute under Customization

**Comment by cwhits** [comment]
@bairdj right, but that's not in the person editor. Also, my google device tracker picture URL changes any time I change my picture with google. I'd like it if the picture were based on the entity_id and would auto update rather than me having to change the url under customization every time I change the picture.

**Comment by iantrich** [comment]
I'm not convinced that we need this. What problem are you trying to solve exactly? I'm going to assume that you want the picture to be represented in a badge, as you can already customize it in the UI anywhere else. If so, good news, you'll be able to set the image for a badge in the next release: https://github.com/home-assistant/home-assistant-polymer/pull/3552

**Comment by ofekashery** [comment]
@iantrich No matter where I use it, you can't set a picture for a person, it uses just an icon.
![image](https://user-images.githubusercontent.com/16443111/64378980-9b127400-d036-11e9-869e-edf91ca67740.png)

**Comment by iantrich** [comment]
Glance card doesn't support images currently. That's a separate issue

**Comment by iantrich** [comment]
That's something I'll look into adding. You shouldn't have to set entity_picture

**Comment by balloob** [comment]
I would love to see a generic image upload backend that can be used for persons, devices and areas.
