### ISSUE TITLE
Context menu does not work on Android Firefox 

### ISSUE THREAD

**Issue by cyberjacob** [home-assistant/home-assistant-polymer#3453]
**Home Assistant release with the issue:**

0.95.4

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Android 7, Miui 10. Firefox mobile 68.0

**Description of problem:**
Context menu on the overview page does not work. When tapping on the icon the menu opens, but selecting an option closes the menu without doing the action.

**Comment by balloob** [comment]
Can confirm. Unused entities works, other options don't 🤔

**Comment by raffertyp1** [comment]
Just adding to this... also _**does not**_ work on iOS safari, iOS official app, and chrome on iOS.  Using iOS 13 beta. However, it _**does**_ work on desktop Firefox 68 and Chrome 76.

**Comment by RomRider** [comment]
It works on Chrome for Android but you have to retry a least 10 times before it does something. Which is I guess the same issue for everyone, could you all try by repeatedly hitting the "unused entities" button for example?

**Comment by balloob** [comment]
Was digging into this one a bit tonight. I can't seem to find any relevant changes to any of the web components involved. I checked youtube.com, as they use the same components and  it looks like they created their own system for dropdowns. Instead of rendering them inline, they have a dropdown rendererer at the bottom of the page that shows a menu aligned to the pressed button.
