### ISSUE TITLE
Show devices with unassigned areas in Area Registry

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3661]
**Home Assistant release with the issue:**
0.98.4

**Description of problem:**
It would be helpful if the Area Registry panel told the user which devices are not currently assigned to an area, and helped guide them to do so.

Concept is very similar to Unused Entities. Maybe call it Unassigned Devices?

This could display underneath the list of Areas:

![unassigned-devices](https://i.imgur.com/omTppIV.png)

(The menu option would only be visible if one or more devices haven't been assigned to an area.)

Clicking on it would bring you to a subpanel with the same device cards view as Integrations has, except it would only display devices that don't have an area assigned to them yet.

**Comment by balloob** [comment]
I don't think that we should have 1 button do something completely different than what all the other options in the menu do. 

Instead, the new devices table that Bram is making should include area as a column. And then we should add a new page that shows all devices, and since it's sortable, people can easily find the ones without an area.

**Comment by SeanPM5** [comment]
Good point, that does sound like a better approach. 

Will close this for now and re-suggest it when the device page idea gets further along.
