### ISSUE TITLE
Change icon color based on state

### ISSUE THREAD

**Issue by jer78** [home-assistant/home-assistant-polymer#3897]
Not sure if this is a bug or if I’m just doing something wrong but for the life of me I cant get the icon to change colors based on whether my switch or input_boolean is on or off. Without the change of color, it’s just an icon? I’m assuming this must be a bug

**Comment by Misiu** [comment]
@iantrich I was going to open a similar issue, but I found this one.
In my case, I have a switch that I want to display in a read-only state. Because this isn't possible yet (I'll open a feature request for this) I've added a template that displays `On` or `Off`, but I can't setup icon color for that template. My switch is blue when is off and yellow when is on (the default behavior). I'd like to do the exact same thing for template - specify an icon and icon color using a template. Something like this:

```
podlogowka_salon_status:
  friendly_name: "Podgłogówka Salon"
  value_template: "{% if is_state('switch.salon', 'on') %}wł.{% else %}wył.{% endif %}"
  icon_template: >-
    {% if is_state('switch.podlogowka_salon', 'on') %}
      mdi:flash
    {% else %}
      mdi:flash-off
    {% endif %}
  icon_color_template: >-
    {% if is_state('switch.podlogowka_salon', 'on') %}
      rgb(253, 216, 53)
    {% else %}
      rgb(68, 115, 158)
    {% endif %}
```
I'm not sure if this is related, but it would be very useful to be able to specify that at entity level.

**Comment by pho3nixf1re** [comment]
@iantrich do you already have that prototyped as a card type somewhere?

**Comment by iantrich** [comment]
Not yet

**Comment by Misiu** [comment]
@iantrich I've forked HA repo and started adding changes to support icon_color_template.
Any chance you could take a look? https://github.com/Misiu/home-assistant/commit/c36fa7c2de95a9d745f8da01acaf9b753bc03454
I've only done sensor, binary sensor and I've added test for it.
If I get approval on that I can add that property to other files (cover, light, switch) and write simple tests.

What format should be supported? 
`#fff000`
`red`
`rgba(250, 114, 122, .5)`

**Comment by iantrich** [comment]
@Misiu yes, a string. That sounds fine by me but it will be a separate PR for the frontend to support that attribute.

I don't really do much backend stuff, I'll leave reviewing of that to more knowledgeable folks

**Comment by iantrich** [comment]
No. https://developers.home-assistant.io/docs/en/frontend_development.html
