### ISSUE TITLE
1 card defined -> more than 1 card seems to be created, causing animation problems...

### ISSUE THREAD

**Issue by MarsWarrior** [home-assistant/home-assistant-polymer#3979]
**Home Assistant release with the issue:**

0.99.3

**Last working Home Assistant release (if known):**
N/A

**UI (States or Lovelace UI?):**

Custom card with Lit-element v2.0.1

**Browser and Operating System:**

Windows 10 with latest Chrome.

**Description of problem:**

I have a custom card included in a horizontal-stack. It is just 1 card with empty custom button cards on either side.

Now it appears after days of debugging that the card is created 1, 2 or 3 times. I can see that because the card constructor is called that many times and the animations are created that many times and running in parallel.

Furthermore:
- always the last created instance receives the `connectedCallback` and `firstUpdated` callback.
- however since `set hass` is called for all the cards and `render()` too, my custom animations are called multiple times. These control some elements in the DOM. And because of multiple parallel animations running on the same elements, causing very bad animations.

**Javascript errors shown in the web inspector (if applicable):**
```
none
```

**Additional information:**
Is this a known issue for other cards?
Without the animation I have no problems, but since I'm adding custom animations using `requestAnimationFrame` this problem of multiple cards instantiated has become a real problem.

I haven't tested yet without the horizontal-stack-card.

**Comment by iantrich** [comment]
sounds like you need to restrict your updates. do you have your source available?

**Comment by AmoebeLabs** [comment]
It seems I'm getting at least 2 updates about 16msec apart when I log the updated() call:

![image](https://user-images.githubusercontent.com/7996307/66603097-b3346080-ebab-11e9-864a-ebc7d06a0636.png)

That seems like the animationFrame lit-element is using to render the card...

I'm also seeing multiple updates with the same data in `set hass`, so that might cause the two renders and thus the two `updated()` calls.

**But that doesn't explain the two calls I see in the constructor:**

![image](https://user-images.githubusercontent.com/7996307/66603422-76b53480-ebac-11e9-927e-40d78aeb0cc0.png)

You see the following (I generate id's for each card and object):
- card constructor is called, id = orywsx3wy
- setConfig is called for that card
==
- Second card constructor is called, id = w749sy2is. ONLY 4msec after the first card!
- setConfig is called for that card
==
- ConnectedCallback for w749... (NEVER for the oryw... card)
- firstUpdated, again only for w749...
- updated, again only for w749

Could you check if that is NOT normal for all native hass cards? Because that would help me a lot. Is it a bug on my side, or a bug in hass 😄 

=====

And this is how an expected animation update should look like. The first large number after the '1' is the starttime: that should be the same for an animation. For the rest you see the progress at the end which starts at 0, and goes up to 1.

![image](https://user-images.githubusercontent.com/7996307/66604166-e4ae2b80-ebad-11e9-9f16-59458db7af75.png)

And when things go wrong, I see this happening. Different progress ('prog' label) causing nasty animations of course on the screen.

![image](https://user-images.githubusercontent.com/7996307/66604604-c694fb00-ebae-11e9-93e0-337526dbfd9a.png)

Still don't know however if these are two different problems:
- card is created twice, but only 1 is connected & updated
- multiple updates from the real and the fake card are messing up the animations
- OR multiple updates from hass are messing up the animations (animation is still running, and a second animation is started, in other words: a bug on my side not handling multiple updates during the animation run).

**Comment by MarsWarrior** [comment]
Jekyll & Hide again 😃

**Comment by iantrich** [comment]
Hass is updated all the time. It's on you to decide if it is an update that you care about or not; e.g. relevant state change

**Comment by MarsWarrior** [comment]
I have put 3 filters now on the cards to filter data & animations. That part works much better.
Setting flags based on the `firstUpdated` and `updated` events seem to filter out most of the problems.

But still of course wondering why I'm getting multple calls to the `constructor()` of the card, `setConfig()` and `set hass()` functions for a single yaml definition.

**Comment by MarsWarrior** [comment]
Small update: After a restart of hass (I upgraded HACS, so needed a restart), I got only 1 call to the constructor and everything is smooth as butter:

![image](https://user-images.githubusercontent.com/1220775/66657577-59ca4100-ec40-11e9-8178-c04a03909635.png)


But after hitting ctrl-F5 on the view with my card, again TWO calls...

![image](https://user-images.githubusercontent.com/1220775/66657688-8b430c80-ec40-11e9-89a2-d6b37d3ad0bb.png)

If I hit ctrl-F5 on another view, and then switch to the view with my card, I get 1 call again...

![image](https://user-images.githubusercontent.com/1220775/66658290-7ca92500-ec41-11e9-837c-464d42db2be5.png)


That is weird. Might this be a browser problem? Not everything is cleaned up after ctrl-F5 ??
Clearing cache & reload (with inspector view open in Chrome) also gives TWO calls to the card...

I haven't noticed this before, but now I understand better why it sometimes worked as expected, and in other cases not: as I'm developing live I use ctrl-F5 to reload my card into hass.
