### ISSUE TITLE
Unable to install package paho-mqtt==1.3.0 version 0.52.0.dev0

### ISSUE THREAD

**Issue by claudius61** [home-assistant/home-assistant-polymer#404]
I 'm newbiee , I copied the repertory 'home assistant' of https://github.com/home-assistant/home-assistant on /usr/local/lib/python3.4/dist-packages/homeassistant of my raspberry. It is insufficient,what must I make of other ?

**Comment by MartinHjelmare** [comment]
First, this is the frontend repository for home assistant. The main repo is over at https://github.com/home-assistant/home-assistant.

Second, please only report bugs in the issue trackers. If you need help, use our help channels.
https://home-assistant.io/help/#communication-channels

If you just want to install home assistant for normal use, follow the install instructions.
https://home-assistant.io/docs/installation/python/

If you want to develop, follow the developer instructions.
https://home-assistant.io/developers/development_environment/

The most common reason why a requirement can't be installed is due to a missing dependency. The pip log should tell you why installation failed, if you try to install the requirement manually at the command line.
```
pip3 install paho-mqtt==1.3.0
```
