### ISSUE TITLE
Generic thermostat "broke font size"

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant-polymer#4157]
Home Assistant release with the issue: 0.101.0

Last working Home Assistant release (if known): 0.100

Operating environment (Hass.io/Docker/Windows/etc.):
 Hass.io on a RPi4

Description of problem: 

Desktop
![shot2](https://user-images.githubusercontent.com/4722227/67977228-fb2d2d00-fc17-11e9-8ea8-5672a7614bdf.JPG)

Mobile
![](https://i.postimg.cc/52JnMQBJ/Screenshot-20191031-193637.jpg)

It is not possible to put two generic_thermostat side by side because fonts are now too big and overlaps with other infos.

Please fix

**Comment by gohassgo** [comment]
Fwiw, I'm running the stock template and don't have this issue.

![image](https://user-images.githubusercontent.com/28564848/67993386-0469ca00-fc17-11e9-8fb9-102018076578.png)

**Comment by sblantipodi** [comment]
related issue #28398
@gohassgo you don't have the issue since you don't have two card side by side in a horizontal layout

**Comment by gohassgo** [comment]
This is a horizontal stack?

**Comment by sblantipodi** [comment]
vertical-stack one sorry

**Comment by 3ative** [comment]
Still not fixed in 0.101.1...

![thermo](https://user-images.githubusercontent.com/51385971/68053010-d487f880-fce2-11e9-92b5-b051183db76a.JPG)

I suspect a change in **UI CSS** / **Theme** / _etc_
Does anyone know if anyone is working on this, what changed...
-  Or a way of fixing it locally _(may be we could have a font size setting in a **theme.yaml** file??? )_ 

I look forward to having my interface looking good again :)

**Comment by bramkragten** [comment]
Yes @thomasloven is working on this

**Comment by 3ative** [comment]
@bramkragten  Good to know, thanks for the info.

**Comment by 3ative** [comment]
@thomasloven 
From what I can gather, your changes have passed all checks, Good job there fella and **THANK YOU** for your work.
How long does these kind of changes take to get to the rest of us?

**Comment by thomasloven** [comment]
I'd guess about three weeks.
