### ISSUE TITLE
Camera detailed view is smaller than group view (iPhone)

### ISSUE THREAD

**Issue by stjohnjohnson** [home-assistant/home-assistant-polymer#44]
When clicking on the camera component to get a live view, the image is smaller than the group level view.

Sample photo (not taken on iPhone, just resized): <img width="502" alt="screen shot 2016-03-28 at 8 47 05 am" src="https://cloud.githubusercontent.com/assets/622065/14081903/dbd3e180-f4c1-11e5-8b6b-a34afd1b0f44.png">

I'm not familiar with this codebase yet.  But do you have recommendations on how to fix this, I'd be happy to contribute the code.

**Comment by balloob** [comment]
This is the way the modal dialog works. I do not want to put in an
exception for just one component so this is pretty much what it is.

On Mon, Mar 28, 2016 at 8:50 AM, St. John Johnson <notifications@github.com>
wrote:

> When clicking on the camera component to get a live view, the image is
> smaller than the group level view.
>
> Sample photo (not taken on iPhone, just resized): [image: screen shot
> 2016-03-28 at 8 47 05 am]
> <https://cloud.githubusercontent.com/assets/622065/14081903/dbd3e180-f4c1-11e5-8b6b-a34afd1b0f44.png>
>
> I'm not familiar with this codebase yet. But do you have recommendations
> on how to fix this, I'd be happy to contribute the code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/balloob/home-assistant-polymer/issues/44>
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by michaelarnauts** [comment]
I'm in favor of removing the extra 24 pixels left and right. This greatly improves the image of the camera when viewed on a mobile device as shown below, it also looks better since the margins are aligned with the "idle" and the thumbnail in the title.

Current dialog:
![before](https://cloud.githubusercontent.com/assets/1193779/16547499/3a90be6e-4170-11e6-998b-98e95cf5a506.PNG)

After removal of 24pixels:
![after](https://cloud.githubusercontent.com/assets/1193779/16547501/3d475bc2-4170-11e6-8b20-c5a4b0a050ad.PNG)

**Comment by michaelarnauts** [comment]
Actually, a simple graph view already has this extra padding removed, so it's not an exception.

![other_view](https://cloud.githubusercontent.com/assets/1193779/16547526/949d031c-4171-11e6-95d4-1f573dc0869b.PNG)
