### ISSUE TITLE
Lovelace Map Card autofocus

### ISSUE THREAD

**Issue by rp3tya** [home-assistant/home-assistant-polymer#4705]
## The request

Currently the map card does not adjust the view when a device's location changes (gets off the map). I have to press the 'Reset Focus' button to get everything in view again. Would like an option to Reset Focus automatically either when a new location is reported or every X seconds.

## The alternatives

Couldn't find any custom map cards.

**Comment by bramkragten** [comment]
Is already implemented in 0.105

**Comment by danwestness** [comment]
I am looking for this same feature. I know it was commented here that this was added in 0.105, however I find no evidence of this.
The behavior is still as descibed running the latest version today. In order to reset focus i either need to manually press the reset focus button or refresh the entire page. This is not ideal as i am running this on a dashboard display that i have to VNC into in order to do either operations whenever people move out of the map's current zoom level.
