### ISSUE TITLE
Various color wheel issues

### ISSUE THREAD

**Issue by jmesberg** [home-assistant/home-assistant-polymer#787]
I'm using the new color wheel with a Fibaro RGBW controller. Overall it works OK, but both on MacOS (tried both Safari & Chrome) and on the iOS Home Assistant app, the overall behavior is not what I'd expect. I have to touch a new location on the wheel at least twice before the color is selected, and often the color that is selected is not that close to where the mouse press or finger touch was. When I drag the circle I get better behavior (i.e. I don't have to drag it twice) but the inaccurate placement issue remains. 

Also, when I'm moving the circle the entire wheel gets "jumpy", i.e. it bounces up and down vertically.

**Comment by raccettura** [comment]
Possibly  related, but at least with my lightify it can disappear for a few seconds once color has changed then reappear.

**Comment by hvbhome** [comment]
Though very nice, use it a lot, it also shows on Philips hue white ambiance lamps which don’t have colors besides the regular color temp? Not very useful possibly confusing to show when not really applicable.

**Comment by NovapaX** [comment]
These are a couple of ussues here:
- The 'jumpiness' is caused by the history chart resetting itself.... (that should have a fixed height)
- The color only getting selected after the second click/tap is a weird issue. On a touch screen it could be that it interpreted it as a scrolling action, which is expected. On mouse input it should just select the color on the first click.  Can you check the logs if it at least sends a state change when this happens?
- The selected color (the marker) not ending up where the touch was is basically the result of the color calculations going wrong.

Some log entries of the state changes when these issues occur would be helpful.

**Comment by NovapaX** [comment]
I'm wondering what your experience is with the light controls in the latest releases.
The chart code got some updates and should not cause erratic movements in the dialog anymore.

The other issues (colors not updating, or updating to a wrong color) are actually a backend/component problem. So I suggest opening an issue there, if it still occurs.

**Comment by raccettura** [comment]
Seems substantially better to me now. 👍
